## 车型特定参数，主要是传感器的杆臂值

[basic_info]
vehicle_info = "SA6H"

# 为了与文档内的杆臂值定义一致，这里杆臂值的描述，自车采用前左上定义，单位为毫米
[lever_FLU] # x-y-z -> 前-左-上 定义，单位 毫米 mm
lever_flu_vehicle_2_gnss_antenna = [-512.12, 440.771, 1568.47] # 自车到卫星天线的杆臂
lever_flu_vehicle_2_imu = [1331.676, 341.4244874, 398.569]     # 自车到IMU的杆臂
