## 车型特定参数，主要是传感器的杆臂值

[basic_info]
vehicle_info = "SF"

# 为了与文档内的杆臂值定义一致，这里杆臂值的描述，自车采用前左上定义，单位为毫米
[lever_FLU] # x-y-z -> 前-左-上 定义，单位 毫米 mm
lever_flu_vehicle_2_gnss_antenna = [-107.58, 0.9, 1861.93] # 自车到卫星天线的杆臂
lever_flu_vehicle_2_imu = [-408.83, 537.91, 734.15]        # 自车到IMU的杆臂
