load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "convert",
    srcs = [
        "convert.cpp",
    ],
    copts = [
        "--std=c++17",
    ],
    deps = [
        "//modules/localization/src/TCMSF/tcmsf/util:file_io_lib",
        "//modules/localization/src/TCMSF/third_party/wgs84_to_mars",
    ],
)

cc_binary(
    name = "convert_nova",
    srcs = [
        "convert_nova.cpp",
    ],
    copts = [
        "--std=c++17",
    ],
    deps = [
        "//modules/localization/src/TCMSF/tcmsf/util:file_io_lib",
        "//modules/localization/src/TCMSF/third_party/wgs84_to_mars",
    ],
)

cc_binary(
    name = "convert_ie",
    srcs = [
        "convert_ie.cpp",
    ],
    copts = [
        "--std=c++17",
    ],
    deps = [
        "//modules/localization/src/TCMSF/tcmsf/util:file_io_lib",
        "//modules/localization/src/TCMSF/third_party/wgs84_to_mars",
    ],
)

cc_binary(
    name = "convert_gnss",
    srcs = [
        "convert_gnss.cpp",
    ],
    copts = [
        "--std=c++17",
    ],
    deps = [
        "//modules/localization/src/TCMSF/tcmsf/util:file_io_lib",
        "//modules/localization/src/TCMSF/third_party/wgs84_to_mars",
    ],
)

cc_binary(
    name = "convert_gt",
    srcs = [
        "convert_gt.cpp",
    ],
    copts = [
        "--std=c++17",
    ],
    deps = [
        "//modules/localization/src/TCMSF/tcmsf/util:file_io_lib",
        "//modules/localization/src/TCMSF/third_party/wgs84_to_mars",
    ],
)